package(default_visibility = ["//visibility:public"])

cc_library(
    name = "idl",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
         "//src/utils:utils",
        "//src/framework:framework",
        "//src/third_party:third_party",
    ],
)