package(default_visibility = ["//visibility:public"])

cc_library(
    name = "easy_dag",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//src/framework:framework",
        "//src/third_party:third_party",
        "//src/idl:idl"
    ],
)